### ISSUE TITLE
Long delay when responding to channel changes

### ISSUE THREAD

**Issue by dave-patterson-bristol** [kangsterizer/Audio_PPM_Linux#4]
I'm seeing about 4 seconds of latency between changing the channel value in the gtk gui and that value change on the sound card.

I'm not much of a python guy by my basic debugging tells me that the value changes are hitting the Signal card.write in near real time but I don't see that change on the radio for 4 seconds.

Thanks for the code. If I can eliminate the lag it's going to be really useful for a project I'm playing with.

**Comment by kangsterizer** [comment]
fixed by.. you :)
