### ISSUE TITLE
PPM for dx6

### ISSUE THREAD

**Issue by Jouwert** [kangsterizer/Audio_PPM_Linux#6]
I really like your project, this is exactly what I need! I'd like to connect my Raspberry Pi 3b to a Spektrum DX6 TC to control a beebrain v2 (acrobee). My goal is to autopilot the acrobee, using the Raspi as the pilot. I'd like to use the trainer/student-mode of the Spektrum DX6 so the PPM signal would go over the audio cable.
Would the program also work for the DX7? I am trying to find the exact channel signal settings in terms of duration and amplitude. Any suggestions where I could find this? Thanks!

**Comment by Jouwert** [comment]
no bother - I bought a dx7s...

**Comment by kangsterizer** [comment]
note, it also works on the dx7 ;-)
